# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HDTMcpp <- function(Y, edge, tau_vec, nu_vec, theta_vec, c, gamma_sample, alpha, mcmc_iter, select) {
    .Call('_DTMM_HDTMcpp', PACKAGE = 'DTMM', Y, edge, tau_vec, nu_vec, theta_vec, c, gamma_sample, alpha, mcmc_iter, select)
}

HDTMcpp_centroid <- function(Y, edge, tau_vec, nu_vec, theta_vec, c, gamma_sample) {
    .Call('_DTMM_HDTMcpp_centroid', PACKAGE = 'DTMM', Y, edge, tau_vec, nu_vec, theta_vec, c, gamma_sample)
}

